-- 쪽지

-- 쪽지 테이블 삭제
DROP TABLE NOTEDB;
-- 쪽지 고유번호 시퀀스 삭제
DROP SEQUENCE NOTESEQ;
-- 쪽지 테이블 생성
CREATE TABLE NOTEDB(
	NOTENUM NUMBER PRIMARY KEY,
	SENDDATE DATE,
	SENDER VARCHAR(20),
	RECEIVER VARCHAR(20),
	TITLE VARCHAR(200),
	CONTENT VARCHAR(2000),
	CHECKS NUMBER,
	DELETED NUMBER
);
-- 쪽지 고유번호 시퀀스 생성
CREATE SEQUENCE NOTESEQ
START WITH 1
NOCACHE;