CREATE TABLE BUY(
	BUYNUM NUMBER,
	EMPNO VARCHAR2(20),
	PROCODE VARCHAR2(20),
	AMOUNT VARCHAR2(10),
	BUYCOMMENT VARCHAR2(500),
	REGDATE DATE,
	APPDATE DATE,
	BUYSTEP NUMBER,
	DELETED NUMBER	
);

CREATE SEQUENCE BUY_SEQ
START WITH 1
NOCACHE;



SELECT * FROM BUY;
DROP TABLE BUY;
DROP SEQUENCE BUY_SEQ


SELECT BUYNUM, MAX(REGDATE) AS REGDATE, COUNT(*) AS CNT, MAX(EMPNO) AS EMPNO, MAX(PROCODE) AS PROCODE, MAX(TEAM) AS TEAM FROM		
		(SELECT B.BUYNUM AS BUYNUM, B.EMPNO AS EMPNO, B.PROCODE AS PROCODE, B.AMOUNT AS AMOUNT, B.BUYCOMMENT AS BUYCOMMENT,
					 B.REGDATE AS REGDATE, B.BUYSTEP AS BUYSTEP , B.DELETED AS DELETED, S.TEAM AS TEAM FROM BUY B, SMEMBER S WHERE B.EMPNO = S.EMPNO) 		
		WHERE BUYSTEP=1 GROUP BY BUYNUM ORDER BY BUYNUM DESC
		