DROP TABLE OREQUEST;
DROP SEQUENCE ONUM_SEQ;  
-------기존 발주관련요청 테이블 삭제-------


CREATE TABLE BUY(
	BUYNUM NUMBER,
	EMPNO VARCHAR2(20),
	PROCODE VARCHAR2(20),
	AMOUNT VARCHAR2(10),
	BUYCOMMENT VARCHAR2(500),
	REGDATE DATE,
	APPDATE DATE,
	BUYSTEP NUMBER,
	DELETED NUMBER	
);


BUYNUM		ID VARCHAR2(50) PRIMARY KEY,
EMPNO			EMPNO VARCHAR2(20),
PROCODE		PROCODE VARCHAR2(20),
AMOUNT		PROAMOUNT NUMBER,
REGDATE		REGDATE DATE,
APPDATE	
					CUSTOMER VARCHAR2(30),
					ADDRESS VARCHAR2(300),
BUYSTEP		CHECKS NUMBER,
DELETED		DELETED NUMBER	
);

CREATE SEQUENCE BUY_SEQq21
START WITH 1
NOCACHE;


UPDATE BUY SET BUYSTEP = 2, APPDATE=SYSDATE WHERE BUYNUM=2
SELECT * FROM BUY;
DROP TABLE BUY;
DROP SEQUENCE BUY_SEQ
UPDATE BUY SET BUYSTEP = 0
SELECT B.BUYNUM AS BUYNUM, B.EMPNO AS EMPNO, B.PROCODE AS PROCODE, B.AMOUNT AS AMOUNT, B.BUYCOMMENT AS BUYCOMMENT,
					 B.REGDATE AS REGDATE, B.BUYSTEP AS BUYSTEP , B.DELETED AS DELETED, P.PRONAME AS PRONAME FROM BUY B, PRODUCT P WHERE B.PROCODE = P.PROCODE
					 
SELECT BUYNUM, MAX(REGDATE) AS REGDATE, COUNT(*) AS CNT, MAX(EMPNO) AS EMPNO,
		MAX(PROCODE) AS PROCODE, MAX(BUYSTEP) AS BUYSTEP, MAX(TEAM) AS TEAM FROM 
		(SELECT B.BUYNUM AS BUYNUM, B.EMPNO AS EMPNO, B.PROCODE AS PROCODE, B.AMOUNT AS AMOUNT, B.BUYCOMMENT AS BUYCOMMENT,
					 B.REGDATE AS REGDATE, B.BUYSTEP AS BUYSTEP , B.DELETED AS DELETED, S.TEAM AS TEAM FROM BUY B, SMEMBER S WHERE B.EMPNO = S.EMPNO)
		WHERE BUYSTEP<2 GROUP BY BUYNUM ORDER BY BUYNUM DESC

SELECT BUYNUM, MAX(REGDATE) AS REGDATE, COUNT(*) AS CNT, MAX(EMPNO) AS EMPNO, MAX(PROCODE) AS PROCODE, MAX(TEAM) AS TEAM FROM		
		(SELECT B.BUYNUM AS BUYNUM, B.EMPNO AS EMPNO, B.PROCODE AS PROCODE, B.AMOUNT AS AMOUNT, B.BUYCOMMENT AS BUYCOMMENT,
					 B.REGDATE AS REGDATE, B.BUYSTEP AS BUYSTEP , B.DELETED AS DELETED, S.TEAM AS TEAM FROM BUY B, SMEMBER S WHERE B.EMPNO = S.EMPNO) 		
		WHERE BUYSTEP=1 GROUP BY BUYNUM ORDER BY BUYNUM DESC
		