CREATE TABLE NOTEDB(
	NOTENUM NUMBER PRIMARY KEY,
	SENDDATE DATE,
	SENDER VARCHAR(20),
	RECEIVER VARCHAR(20),
	TITLE VARCHAR(200),
	CONTENT VARCHAR(2000),
	CHECKS NUMBER,
	DELETED NUMBER
);

CREATE SEQUENCE NOTESEQ
START WITH 1
NOCACHE;

INSERT INTO NOTEDB (NOTENUM, SENDDATE, SENDER, RECEIVER, TITLE, CONTENT, CHECKS, DELETED)
VALUES(NOTESEQ.NEXTVAL, SYSDATE, '100', '300301', '물건 개 많이 팔아와라 제발 진짜 내가 소망한다', '내가 사장인데', 0, 0);
INSERT INTO NOTEDB (NOTENUM, SENDDATE, SENDER, RECEIVER, TITLE, CONTENT, CHECKS, DELETED)
VALUES(NOTESEQ.NEXTVAL, SYSDATE, '300301', '100', '미안', '앞으로도 계속 할게', 0, 0);