SELECT * FROM SALESBOARD;
DROP TABLE SALESBOARD;
DROP SEQUENCE CALREG;

CREATE TABLE NOTICE(
  NUM NUMBER, 
  NAME VARCHAR2(50), 
  TITLE  VARCHAR2(500), 
  CONTENT  VARCHAR2(3000), 
  REGDATE  DATE
  );

CREATE SEQUENCE NOTICE_SEQ
START WITH 1
NOCACHE;

SELECT * FROM NOTICE;
