CREATE TABLE OREQUEST(
	ONUM NUMBER,
	EMPNO VARCHAR2(20),
	PROCODE VARCHAR2(20),
	OAMOUNT NUMBER,
	OCOMMENT VARCHAR2(500),
	OURL VARCHAR2(500),
	OPRICE NUMBER,	
	REGDATE DATE,
	CHECKS NUMBER,
	DELETED NUMBER	
);

SELECT * FROM OREQUEST;
DROP TABLE OREQUEST;
DROP SEQUENCE ONUM_SEQ
SELECT ONUM, MAX(REGDATE) AS REGDATE, COUNT(*) AS CNT, MAX(EMPNO) AS EMPNO, MAX(PROCODE) AS PROCODE FROM OREQUEST WHERE EMPNO='100' AND CHECKS=0 GROUP BY ONUM ORDER BY ONUM DESC

CREATE SEQUENCE ONUM_SEQ
START WITH 1
NOCACHE;

INSERT INTO OREQUEST(ONUM, EMPNO, PROCODE, OAMOUNT, OCOMMENT, REGDATE, CHECKS, DELETED)
		VALUES((SELECT MAX(ONUM) FROM OREQUEST), '100', '1005', 100, '필요해', SYSDATE, 0, 0);
		
INSERT INTO OREQUEST(ONUM, EMPNO, PROCODE, OAMOUNT, OCOMMENT, REGDATE, CHECKS, DELETED)
		VALUES(ONUM_SEQ.NEXTVAL, '100', '1005', 100, '필요해', SYSDATE, 0, 0);
		
		TO_CHAR(ONUM_SEQ.NEXTVAL), '100', '1005', 100, '필요해', SYSDATE, 0, 0);
		
INSERT INTO OREQUEST(ONUM, EMPNO, PROCODE, OAMOUNT, OCOMMENT, REGDATE, CHECKS, DELETED)
		VALUES(TO_CHAR(ONUM_SEQ.CURRVAL), '300300', '1015', 100, '필요하다고', SYSDATE, 0, 0);