CREATE TABLE ORDERS(
	ID VARCHAR2(50) PRIMARY KEY,
	EMPNO VARCHAR2(20),
	PROCODE VARCHAR2(20),
	PROAMOUNT NUMBER,
	REGDATE DATE,
	CUSTOMER VARCHAR2(30),
	ADDRESS VARCHAR2(300),
	CHECKS NUMBER,
	DELETED NUMBER	
);

SELECT * FROM ORDERS;

CREATE SEQUENCE ORDERID
START WITH 1
NOCACHE;