CREATE TABLE SALARY(
	EMPNO VARCHAR2(20),
	SALARYDATE date,
	SALARY NUMBER,
	ALLOWANCE NUMBER,
	MANAGER NUMBER,
	TAX1 NUMBER,
	TAX2 NUMBER,
	REALS NUMBER
)
SELECT TEAM FROM SMEMBER WHERE TEAM!='관리팀' GROUP BY TEAM ORDER BY TEAM
SELECT S.* FROM SMEMBER S, SMEMBER M WHERE S.EMPNO=M.EMPNO AND S.TEAM!='관리팀' 
SELECT SALARYDATE FROM SALARY GROUP BY SALARYDATE ORDER BY SALARYDATE DESC
select * from salary wher
and o.empno=300301
SELECT * FROM SMEMBER WHERE TEAM!='관리팀'
SELECT S.EMPNO AS EMPNO, M.TEAM AS TEAM, M.AUTH AS AUTH,
S.SALARYDATE AS SALARYDATE, S.SALARY AS SALARY,
S.ALLOWANCE AS ALLOWANCE, S.MANAGER AS MANAGER,
S.TAX1 AS TAX1, S.TAX2 AS TAX2, S.REALS AS REALS
FROM SALARY S, SMEMBER M WHERE S.EMPNO = M.EMPNO
ORDER BY S.SALARYDATE DESC, M.TEAM, M.AUTH DESC

SELECT S.ID AS ID, S.EMPNO AS EMPNO, S.REGDATE AS REGDATE,
			M.NAME AS NAME, M.TEAM AS TEAM, M.AUTH AS AUTH,
			S.PROCODE AS PROCODE, P.PRONAME AS PRONAME, S.PROAMOUNT AS PROAMOUNT,
			((P.SELLPRICE-P.ORIGINPRICE)*S.PROAMOUNT) AS PROFIT,
			S.CUSTOMER AS CUSTOMER, S.ADDRESS AS ADDRESS, S.CHECKS AS CHECKS,
			S.DELETED AS DELETED
			FROM ORDERS S, 
			(SELECT EMPNO, NAME, TEAM, AUTH FROM SMEMBER) M,
			(SELECT PROCODE, PRONAME, PROAMOUNT, ORIGINPRICE, SELLPRICE FROM PRODUCT) P
			WHERE S.EMPNO=M.EMPNO AND S.PROCODE=P.PROCODE AND DELETED=0 AND CHECKS=1
			