DROP TABLE SMEMBER;
delete from smember;
SELECT * FROM SMEMBER;
SELECT * FROM SMEMBER WHERE AUTH NOT LIKE 'ROLE_EE' AND name LIKE 'dd'
SELECT EMPNO AS USERID, PWD AS PASSWD, 1 ENABLED FROM SMEMBER
										WHERE EMPNO=100;
										SELECT TEAM FROM SMEMBER WHERE TEAM LIKE '영업%' GROUP BY TEAM ORDER BY TEAM
										SELECT TEAM FROM SMEMBER GROUP BY TEAM ORDER BY TEAM
SELECT EMPNO, AUTH FROM SMEMBER WHERE EMPNO=100;
SELECT EMPNO AS USERID, PWD AS PASSWD, 1 ENABLED FROM SMEMBER
--EMPNO		= ID ���� �� ���
--PWD		= ��й�ȣ
--NAME		= �̸�
--GENDER	= ����
--BIRTH		= ����
--JOIN		= �Ի���
--ADDRESS	= �ּ�
--PHONE		= ��ȭ��ȣ
--EMAIL		= �̸���
--AUTH		= ����
--PORTRAIT	= �������
--ACCOUNT	= ���¹�ȣ
--TEAM		= ��
CREATE TABLE SMEMBER(
	EMPNO VARCHAR2(10) PRIMARY KEY,
	PWD VARCHAR2(30) NOT NULL,
	NAME VARCHAR2(20) NOT NULL,
	GENDER VARCHAR2(10),
	BIRTH DATE,
	JOIN DATE,
	ADDRESS VARCHAR2(180),
	PHONE VARCHAR2(20) NOT NULL,
	EMAIL VARCHAR2(30),
	AUTH VARCHAR2(20) NOT NULL,
	PORTRAIT VARCHAR2(200),
	ACCOUNT VARCHAR2(50) NOT NULL,
	TEAM VARCHAR2(20) NOT NULL
);

CREATE SEQUENCE NUMREGISTER
START WITH 300300
NOCACHE;
delete from smember where empno=100
INSERT INTO SMEMBER (EMPNO, PWD, NAME, GENDER, BIRTH, JOIN, ADDRESS, PHONE, EMAIL, AUTH, PORTRAIT, ACCOUNT, TEAM) 
VALUES('100', 'oracle', '관리자', '남', date '2000-1-1', date '2000-1-1', '코스타', '010-0000-0000', 'kosta@kosta', 'ROLE_ADMIN', 'kost_logo.png', '01-4829-333-2201', '관리팀');
INSERT INTO SMEMBER (EMPNO, PWD, NAME, GENDER, BIRTH, JOIN, ADDRESS, PHONE, EMAIL, AUTH, PORTRAIT, ACCOUNT, TEAM) 
VALUES(to_char(numregister.nextval), 'oracle', '����', '��', date '1985-9-25', date '2010-4-27', '�츮����', '010-9459-2077', 'leesolge@gmail.com', 'ROLE_EE', null, '01-4829-333-2201', '����1��');