SELECT * FROM (SELECT ROWNUM R, T.* FROM (SELECT O.ID AS ID, O.EMPNO AS EMPNO, O.REGDATE AS REGDATE,
			S.NAME AS NAME, S.TEAM AS TEAM, S.AUTH AS AUTH,
			O.PROCODE AS PROCODE, P.PRONAME AS PRONAME, O.PROAMOUNT AS PROAMOUNT,
			((P.SELLPRICE-P.ORIGINPRICE)*O.PROAMOUNT) AS PROFIT,
			O.CUSTOMER AS CUSTOMER, O.ADDRESS AS ADDRESS, O.CHECKS AS CHECKS,
			O.DELETED AS DELETED
			FROM ORDERS O, 
			(SELECT EMPNO, NAME, TEAM, AUTH FROM SMEMBER) S,
			(SELECT PROCODE, PRONAME, PROAMOUNT, ORIGINPRICE, SELLPRICE FROM PRODUCT) P
			WHERE O.EMPNO=S.EMPNO AND O.PROCODE=P.PROCODE AND DELETED=0 ORDER BY O.REGDATE DESC) T)
			WHERE R>=1 AND R<=10